apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  labels:
    app: vpromq01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpromq01
  template:
    metadata:
      labels:
        app: vpromq01
    spec:
      containers:
        - name: vpromq01
          image: rabbitmq:3-management
          ports:
            - name: amqp-port
              containerPort: 5672
            - name: management-port
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: rmq_pass
            - name: RABBITMQ_DEFAULT_USER
              value: guest

---
apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  ports:
    - port: 5672
      targetPort: amqp-port
      protocol: TCP
    - port: 15672
      targetPort: management-port
      protocol: TCP
  selector:
    app: vpromq01
  type: ClusterIP
